name: app_teste1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.16.0
  image_picker: ^1.0.0
  firebase_storage: ^11.5.6
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  http: ^0.13.5     
  smooth_page_indicator: ^1.1.0
  flutter_animate: ^4.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.6

flutter_icons:
  image_path: "assets/icons/dog.png"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#FFA726" # ou `background_image: "assets/splash/bg.png"`
  image: "assets/icons/dog.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
    
